[LLAMA-7B]
network = FlowNet
seed-set = 42
result-dir = results/${configname}
# sim-time-limit = 1s
# cpu-time-limit = 10s  # 限制CPU时间
debug-on-errors = true  # 出错时进入调试模式
# output-log = "output.log" # 输出日志文件

*.job_cnt = 1
*.Mode = ${Mode=0,1,2,3}

# Fat-Tree参数
*.leaf_server_degree = 8
*.spine_leaf_degree = 4
*.spine_core_degree = 4
*.pod_cnt = 4
*.linkCapacity = 1e11 # 100G
*.ScaleUpCapacity = 8e12 # 1TB = 8Tbps
*.gpusPerServer = 8  # 每台服务器的CPU数量

*.switch_limit = ${switch_limit=4,8,16,32}
#*.switch_limit = 10

# 任务参数
# GPT-3 175B on 1024 GPUs
*.iterations = 3
*.TP = 8
*.PP = 1
*.DP = 16 #  1024/4/8=32
*.num_layers = 32
*.hidden_size = 4096
*.num_parameters = 6.7e9
*.num_tokens_per_seq = 4096
*.batch_size = 128
*.dtype_size = 16 # bits    
*.gpu_flops = 312e12 # NVIDIA V100 32GB：125TFLOPS